### ISSUE TITLE
Thermal imagery normalization

### ISSUE THREAD

**Issue by pbaer** [Microsoft/arcticseals#4]
Our thermal data is in a raw 16-bit PNG format. We need to both a) figure out exactly what the raw values correspond to so that we can normalize the data (i.e. 0 degrees Celsius should be the same 16-bit pixel value in any image) for training and b) convert it an 8-bit representation for human visual inspection.

**Comment by Marcel-Simon** [comment]
It seems the reason why the 16 bit images are all gray is because the values are all pretty high:

    In: np.unique(img, return_counts=True)
    Out: (array([51241, 51361, 51381, 51401, 51421, 51441, 51461, 51481, 51501,
            51521, 51541, 51561, 51581, 51601, 51621, 51641, 51661, 51681,
            51701, 51721, 51741, 51761, 51781, 51801, 51821, 51841, 51861,
            51881, 51901, 51921, 51941, 51961, 51981, 52001, 52021, 52041,
            52061, 52101, 52181]),
     array([    1,     2,    13,     6,    31,    50,   204,   313,   880,
             1086,  3079,  6116, 11211, 12168, 27619, 25012, 45961, 33892,
            50997, 30580, 34756, 14925, 13214,  5228,  4758,  1819,  1709,
              762,   615,   323,   163,    80,    40,    35,    10,     8,
               10,     2,     2], dtype=int64))

However, the image reading itself seems fine. For example, try this:

    img = np.array(PIL.Image.open(image_path))
    mi = np.percentile(img, 1)
    ma = np.percentile(img, 99)
    plt.imshow((img - mi)/(ma-mi), vmin=0, vmax=1)

It is also important to set `vmin=0, vmax=1` when using pyplot, as it will mess up scaling because there are negative and values >1 in the array after normalization.

**Comment by jomalsan-MSFT** [comment]
The normalization that you have above will work for viewing the images, however I would not train on data that has been normalized in this way. Because the normalization takes the entire image into account, the portion of the image that contains a seal will be different numerically depending on if the image is primarily ice (low value) or liquid (high  value)

**Comment by Marcel-Simon** [comment]
It's true that the distribution might be very different locally. It would be helpful to get some statistics as this issue certainly influences the architecture of recognition models. Let's make a possible action item out of this: 

- Collect statistics of the IR image values across different images and for local regions containing seals. This could be as simple as an histogram, but we also need a way to compare the statistics of different images and somehow measure how different they are from each other. It would be also good to know, if the temperature value of the seals is consistent or not.

**Comment by jomalsan-MSFT** [comment]
I am working on putting together a Jupyter notebook that explains what we currently know and then building a python script for other people to include

**Comment by jomalsan-MSFT** [comment]
Thanks to Eric for his help on this project. The code is checked into "src/ir-normalization" and the normalized images have been added as a tar file to blob storage as "ArcticSealsTrain1807221152_N.tar".  For the new normalized 8-bit thermal images, we have changed "16BIT" to "8BIT_N" in the file names to keep it straight.

**Comment by pbaer** [comment]
I'll generate a new training/test set with the full labeled IR imagery soon. Marcel, I could prepare VOTT annotations for animals only (as last time), or for both animals and anomalies, ie one or two classes. Thoughts on which is preferable?

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by Marcel-Simon** [comment]
I think we only need the ones with animals inside. Could you also copy both the 16bit IR (or our 8bit normalized version) and the color version for each image? I'd run Neels code on it to get the combined images.
________________________________
